### ISSUE TITLE
How will it work in case of inherited HTML tags (custom elements) and Shadow DOM (including closed DOM)?

### ISSUE THREAD

**Issue by serj-kzv** [NDevTK/AutoPause#1]
How will it work in case of inherited HTML tags (custom elements)  and Shadow DOM (including closed DOM)?

1. I can create [custom elements](https://developer.mozilla.org/en-US/docs/Web/API/Window/customElements) that inherits `HTMLVideoElement`
	```js
	class PopupInfo extends HTMLVideoElement {
	}
	customElements.define('popup-info', PopUpInfo);
	````
	How will your algorithm find `<popup-info>` tag?
2. It also should not work with Shadow DOM including **closed** Shadow DOM see my issue for SingleFile addon https://github.com/gildas-lormeau/SingleFile/issues/518

Also see https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements

**Comment by serj-kzv** [comment]
3. It also possible that a **new** `video` or `audio` tag will be added to a page after you sent a `stop` command. So your `stop` command will not work for the **new** tag. It is also possible that the **new** tag will be added in a gap between you switch on another tab and `video` or `audio` tag is found (search algorithm).

**Comment by NDevTK** [comment]
@serj-kzv I was unable to check for its now checking for HTMLMediaElement https://github.com/NDevTK/AutoPause/commit/013b177dca3977d23495fd48b7c5491b164010de does this fix the issue with 
custom elements? if not please provide an example video.

This always has `document.onplay = main` so if a  new video starts playing it will get paused.
I current dont know what I should change for Shadow DOM.

**Comment by NDevTK** [comment]
Have not found a HTMLVideoElement using a different tag then "video"

**Comment by NDevTK** [comment]
Should be fixed now!

**Comment by NDevTK** [comment]
Thanks for the report @serj-kzv
This is finally fixed as of https://github.com/NDevTK/AutoPause/actions/runs/1726036383 I tested it using a closed shadow dom https://ndevtk.github.io/AutoPause/shadow.html
