### ISSUE TITLE
Go to Active Tab Hotkey

### ISSUE THREAD

**Issue by jesse9212** [NDevTK/AutoPause#2]
This plugin is Genius!

A hotkey or button to go to active playing tab would be great! Sometimes its hard to find or see the music icon amongst all the tabs.

Cheers!!!

**Comment by NDevTK** [comment]
@jesse9212 code has now been added https://github.com/NDevTK/AutoPause/commit/f6845cc84801700752e07cb0fa289e8b8b265645 this can be used with
Ctrl+Shift+K

**Comment by jesse9212** [comment]
Getting this console error when using it:

`MouseEvent.mozPressure is deprecated. Use PointerEvent.pressure instead.`

**Comment by NDevTK** [comment]
I dont think this is warning is from the extension as it does not use the MouseEvent.

**Comment by jesse9212** [comment]
In that case, the hotkey is bringing up the error console for me instead of the intended effect.

**Comment by jesse9212** [comment]
In that case, the hotkey is bringing up the error console for me instead of
the intended effect.

**Comment by NDevTK** [comment]
Yeah theirs a conflict https://developer.mozilla.org/en-US/docs/Tools/Keyboard_shortcuts
My fault for testing with chrome.

**Comment by NDevTK** [comment]
Changed it to Shift+K
