### ISSUE TITLE
Can't change settings when extensions.webextensions.remote = false

### ISSUE THREAD

**Issue by name-snrl** [NDevTK/AutoPause#29]
**Describe the bug**

https://user-images.githubusercontent.com/72071763/181287163-d62c35f6-ae32-4f96-be5d-0230e5206dae.mp4

**To Reproduce**
Go to the addon preferences and try changing it.

**Expected behavior**
The settings are saved.

 - OS: NixOS 22.05
 - Browser Mozilla Firefox 102.0.1

**Comment by NDevTK** [comment]
Did you press enter after?

**Comment by name-snrl** [comment]
> Did you press enter after?

yeap

**Comment by NDevTK** [comment]
Normally when pressing enter it will ask for permission.
![expected - Copy](https://user-images.githubusercontent.com/31563761/181292045-840de62a-7547-40d6-a0c5-62950b6f3f71.png)

**Comment by NDevTK** [comment]
Try using the permission tab instead should also work for <all_urls>

**Comment by name-snrl** [comment]
> Normally when pressing enter it will ask for permission. ![expected - Copy](https://user-images.githubusercontent.com/31563761/181292045-840de62a-7547-40d6-a0c5-62950b6f3f71.png)

Not in my case.

When I switched the resolution manually it worked, thanks

**Comment by NDevTK** [comment]
It looks like you have a different content-security-policy so JS cant run in the options page.
Shortcuts does not show any Shortcuts.

Not sure why that would get changed,

**Comment by NDevTK** [comment]
I will try to repo this issue on NixOS
guessing its the normal firefox version with the store version of the extension.

**Comment by NDevTK** [comment]
Tried on NixOS are you using a fork of firefox and are you using the version in the webstore?

**Comment by name-snrl** [comment]
> Try using the permission tab instead should also work for <all_urls>

Yeah, for some reason I had `extensions.webextensions.remote = false` option in my user.js. Thanks, again. Think this can be closed

**Comment by name-snrl** [comment]
p.s. my bad, started the issue, without checking on clear profile

**Comment by NDevTK** [comment]
This preference is used to disable out-of-process extensions, which is an unsupported configuration.
The preference will be removed in a future update ([bug 1613141](https://bugzilla.mozilla.org/show_bug.cgi?id=1613141)).
