### ISSUE TITLE
[Feature Request] Options to disable auto-resume feature

### ISSUE THREAD

**Issue by IAmNotAJerk** [NDevTK/AutoPause#3]
Though I understand some people love the auto-resume feature, but I don't like it that much and would rather resume manually. 

This is such a great addon, btw!

**Comment by NDevTK** [comment]
Hi, @IAmNotAJerk 
Did you want this option added to the context menu of the extension?

**Comment by IAmNotAJerk** [comment]
It doesn't matter to me. Though I'm using this on firefox, extensions usually allow to be configured through a "manage extension" click and lead strict to a firefox addon menu. But that doesn't matter that much, anyway would be great as long as the options are there.

**Comment by NDevTK** [comment]
ok

**Comment by NDevTK** [comment]
You can test it now toggle it with alt+r

**Comment by NDevTK** [comment]
@IAmNotAJerk this has been added in version 1.4 and can be toggled with alt+r

I know it toke a while.
