### ISSUE TITLE
Can't customize keyboard shortcuts

### ISSUE THREAD

**Issue by arousle** [NDevTK/AutoPause#30]
**Describe the bug**
I can no longer customize the keyboard shortcuts in the AutoPause's add-on options.
Selecting one of the text fields in the "Shortcuts" section will allow me to type in the text field, but this won't actually set a keyboard shortcut.

**To Reproduce**
1. Go to 'about:addons' > 'Manage Your Extensions' > 'AutoPause' > '...' > 'Options'.
2. Select one of the text fields in the "Shortcuts" section and try to customize a keyboard shortcut.
3. The shortcut won't be changed.

**Expected behavior**
The keyboard shortcut is set.

**Video**
https://user-images.githubusercontent.com/1099659/184532142-7f210ffc-5d20-424f-8647-215966a0c22d.mp4

**Desktop:**
 - OS: Windows 11, build 22000.795
 - Browser: Firefox 103.0.2 (64-bit)

**Extension configuration**
- Version: 2.7.6, but happens with older versions as well.
- Options changed: none

**Browser configuration**
 - Fresh Firefox install on a sandboxed OS with no other extensions installed.

**Comment by NDevTK** [comment]
Works for me on the latest firefox version.

Did you press enter after making the change?
Also make sure no other shortcut is using the same value as that may conflict.

You can also change shortcuts using the native settings https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox

**Comment by NDevTK** [comment]
@arousle do you still have the issue?

**Comment by arousle** [comment]
The "Manage Extension Shortcuts" workaround works for me. Thanks.
