### ISSUE TITLE
doesn't work on many sites .. 

### ISSUE THREAD

**Issue by pileofuntimes** [NDevTK/AutoPause#4]
listening to wrif.com , switch tabs to youtube and they both play .. watching USTVGO , change tabs to another USTVGO and both play .. i love the idea of this addon and hope you can get it working across the board!  thanks and have a great day!

**Comment by NDevTK** [comment]
hi @pileofuntimes I will check this now.

**Comment by NDevTK** [comment]
The issue for wrif.com is that a html element is not created `window.audioplayer = new Audio(t);`

**Comment by NDevTK** [comment]
@pileofuntimes it now seems to support USTVGO :D

**Comment by pileofuntimes** [comment]
awesome , i will try it out .. thank you for this cool addon!

**Comment by NDevTK** [comment]
@pileofuntimes it now also works on https://wrif.com!
Please verify this it may also work on other websites now.

**Comment by NDevTK** [comment]
The bug has now been fixed.

**Comment by NDevTK** [comment]
Fixed in version 1.2
