### ISSUE TITLE
Suggestion. "Pause all" hotkey or/and queue limit

### ISSUE THREAD

**Issue by ilapro53** [NDevTK/AutoPause#43]
When I open multiple tabs with media playing, a queue of paused media is formed. Sometimes this is very convenient, but if there are too many paused media, it can be difficult to pause them all.

I suggest adding a hotkey to pause all media (i.e. to clear the queue and stop the playing media)

I would also suggest adding a limit to the queue size. The oldest media that exceed the limit will be stopped permanently without automatic continuation.

Sorry for the machine translation

**Comment by NDevTK** [comment]
Seems currently the only way to pause all media is to enable 'checkidle' and lock the device https://github.com/NDevTK/AutoPause/blob/7ef5370b2c85f2df925ec85a900e112538cbfeab/background.js#L534

I should be able to add a hotkey to pause all without resuming other media without clearing the queue. (fix togglePlayback) would that work for you?

**Comment by NDevTK** [comment]
Using the build https://github.com/NDevTK/AutoPause/actions/runs/7714042471 does the "togglePlayback" fix your issue?

Currently the design works assuming all media gets tracked not just the top x however what limit would be good?

**Comment by NDevTK** [comment]
I have now setup a basic system to stop autoresume after 5 tabs :)

**Comment by ilapro53** [comment]
> Seems currently the only way to pause all media is to enable 'checkidle' and lock the device
> 
> https://github.com/NDevTK/AutoPause/blob/7ef5370b2c85f2df925ec85a900e112538cbfeab/background.js#L534
> 
> I should be able to add a hotkey to pause all without resuming other media without clearing the queue. (fix togglePlayback) would that work for you?

If I understand correctly, then yes, this solution would be wonderful!

**Comment by ilapro53** [comment]
> Using the latest build https://github.com/NDevTK/AutoPause/actions/ does the "togglePlayback" fix your issue?
> 
> Currently the design works assuming all media gets tracked not just the top x however what limit would be good?



> I have now setup a basic system to stop autoresume after 5 tabs :)

I installed the extension for Firefox from here: https://github.com/NDevTK/AutoPause/actions/runs/7735249011. I noticed a new option "Dont resume old media" and enabled it. But I checked on 15 YouTube Music tabs: I turned on one by one from tab 1 to tab 15, then stopped from 15 to 2. Only tab 1 did not start playing automatically. Turning off "Dont resume old media" doesn't seem to change anything 🤔

**Comment by ilapro53** [comment]
Oh, sorry. It seems the Toggle Playback feature was present in the old version. I missed it. [In the last build (1304)](https://github.com/NDevTK/AutoPause/actions/runs/7743322335) it works too. 

About "Dont resume old media": [in the last build (1304)](https://github.com/NDevTK/AutoPause/actions/runs/7743322335) it doesn't work, but it works in [build 1299](https://github.com/NDevTK/AutoPause/actions/runs/7743322335) (as expected 5 tabs continued to play)

**Comment by NDevTK** [comment]
Oh nice so do you think this issue is now resolved?

**Comment by NDevTK** [comment]
I will now start the process of testing + publishing the build https://github.com/NDevTK/AutoPause/actions/runs/7746163299

**Comment by ilapro53** [comment]
> Oh nice so do you think this issue is now resolved?

I think yes. I would suggest adding field for custom amount of "not old tabs" if "Dont resume old media" will work, but it's up to you

**Comment by ilapro53** [comment]
> I will now start the process of testing + publishing the build https://github.com/NDevTK/AutoPause/actions/runs/7746163299

It seems that "Dont resume old media" also don't work in this build.

**Comment by NDevTK** [comment]
Yeah should be fixed in https://github.com/NDevTK/AutoPause/actions/runs/7746380808

Lost code from the merge

**Comment by NDevTK** [comment]
If I was not the only one coding it maybe there would be tests to catch stuff like this but nope :(

**Comment by ilapro53** [comment]
> If I was not the only one coding it maybe there would be tests to catch stuff like this but nope :(

I'd like to help, but I'm afraid I only know Python 😢

**Comment by NDevTK** [comment]
Good news this issue should now be fixed in 2.8.4 currently released on chrome and firefox.  :)

Regarding only knowing Python... you can look at the code and guess.

**Comment by NDevTK** [comment]
Please confirm the issue is fixed in the latest extension version 2.8.4 so this can be closed.

**Comment by ilapro53** [comment]
> Good news this issue should now be fixed in 2.8.4 currently released on chrome and firefox. :)

Thanks, is works!



> Regarding only knowing Python... you can look at the code and guess.

Maybe I'll check your repository from time to time)
